REFERENCE=/mnt/e/diana/mirna_vaca/RNASeq_vaca/genome_vaca/genome/bosTau8.fa

TARGETS=`{find /mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/ \
	-name '*_trimmed.fastq.gz' \
| sed -e 's#/mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/#/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/#g' \
	-e 's#_trimmed.fastq.gz#.sam#g' \
}

alignments:V:	$TARGETS

/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sai:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/%_trimmed.fastq.gz
	stem=$stem
        bash -c ". /mnt/e/diana/mirna_vaca/bwa_env/bin/activate /mnt/e/diana/mirna_vaca/bwa_env/
	bwa aln \
                $REFERENCE \
                '/mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/'$stem'_trimmed.fastq.gz' \
                > '/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sai' || exit 1
	. /mnt/e/diana/mirna_vaca/bwa_env/bin/deactivate"


/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sam:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/%_trimmed.fastq.gz \
/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sai
	stem=$stem
	bash -c ". /mnt/e/diana/mirna_vaca/bwa_env/bin/activate /mnt/e/diana/mirna_vaca/bwa_env/
	bwa samse \
		$REFERENCE \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sai' \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/clipped_fastq_vaca/'$stem'_trimmed.fastq.gz' \
		> '/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sam' || exit 1
	. /mnt/e/diana/mirna_vaca/bwa_env/bin/deactivate"
