TARGETS=`{find /mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/ \
        -name '*.sa*' \
&& \
find /mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/ \
        -name '*.sam' \
| sed -e 's#.sam#.unsorted.bam#g' \
&& \
find /mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/ \
        -name '*.sam' \
| sed -e 's#.sam#.bam#g' \
&& \
find /mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/ \
        -name '*.sam' \
| sed -e 's#.sam#.bam.bai#g' \
}

annotate:V:	$TARGETS

/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.unsorted.bam:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sam
	stem=$stem
	samtools view -bS \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sam' \
		> '/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.unsorted.bam' || exit 1

/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sorted.bam:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.unsorted.bam 
	stem=$stem
	samtools sort \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.unsorted.bam' \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sorted' || exit 1

/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.bam:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.sorted.bam 
	stem=$stem
	mv \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.sorted.bam' \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.bam' || exit 1

/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.bam.bai:D:	\
/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/%.bam
	stem=$stem
	samtools index \
		'/mnt/e/diana/mirna_vaca/RNASeq_vaca/mapping_vaca/'$stem'.bam' || exit 1
